name: Tag on Release Merge

on:
  workflow_dispatch:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - "master"
      
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  create_tag:
    # if: startsWith(github.event.head_commit.message, 'debug') && contains(github.event.head_commit.message, 'debug')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Print GitHub context
      run: | 
        echo "$GITHUB_CONTEXT"

    - name: Extract version from branch name
      id: extract_version
      run: |
        BRANCH_REF=${{ github.event.pull_request.head.ref }}
        echo $BRANCH_REF
        if [[ $BRANCH_REF =~ release-([0-9]+)-([0-9]+)-([0-9]+) ]]; then
          VERSION="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.${BASH_REMATCH[3]}"
          echo "version=$VERSION" >> "$GITHUB_ENV"

        else
          echo "Branch name does not match pattern"
          exit 1
        fi

    - name: Create and push tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag -a "$VERSION" -m "Release $VERSION"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} "$VERSION"

