name: Tag on Release Merge

on:
  workflow_dispatch:

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  create_tag:
    # if: startsWith(github.event.head_commit.message, 'debug') && contains(github.event.head_commit.message, 'debug')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Print GitHub context
      run: | 
        echo "$GITHUB_CONTEXT"
        echo "${{ github.event.pull_request.head.ref_name}}"
        echo "${{ github.ref_name }}"

    - name: Extract version from branch name
      id: extract_version
      run: |
        BRANCH_REF=${{ github.event.pull_request.head.ref_name }}
        if [[ $BRANCH_REF =~ release-([0-9]+)-([0-9]+)-([0-9]+) ]]; then
          VERSION="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.${BASH_REMATCH[3]}"
          echo "::set-output name=version::$VERSION"
        else
          echo "Branch name does not match pattern"
          exit 1
        fi

    - name: Create and push tag
      run: |
        VERSION=${{ steps.extract_version.outputs.version }}
        git tag -a "$VERSION" -m "Release $VERSION"

        git push origin "$VERSION"

