name: Tag on Release Merge

on:
  push:
    branches:
      - master

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the branch name
        id: get_branch
        run: |
          BRANCH_REF=$(echo ${{ github.event.ref }} | sed 's|refs/heads/||')
          echo "branch_ref=$BRANCH_REF" >> $GITHUB_ENV
          echo "Branch ref: $BRANCH_REF"

      - name: Check if branch matches release pattern
        id: check_branch
        run: |
          if [[ "${{ steps.get_commit_message.outputs.message }}" =~ ^Merge\ pull\ request\ #[0-9]+\ from\ .*/release_[0-9]+_[0-9]{2}_[0-9]+$ ]]; then
            echo "::set-output name=match::true"
          else
            echo "::set-output name=match::false"
          fi

      - name: Create and push tag
        if: steps.check_branch.outputs.match == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${{ env.branch_ref }}
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
          git push origin "$TAG_NAME"
